apiVersion: v2
name: k8s_gateway
description: A Helm chart for the k8s_gateway CoreDNS plugin
type: application
version: 2.6.0-3
appVersion: 0.6.0
maintainers:
  - email: rawmind@gmail.com
    name: Rawmind
