FROM debian:stable-slim

RUN apt-get update && apt-get -uy upgrade
RUN apt-get -y install ca-certificates && update-ca-certificates

FROM gcr.io/distroless/static:nonroot

COPY --from=0 /etc/ssl/certs /etc/ssl/certs
COPY coredns /coredns

USER 65532:65532

ENTRYPOINT ["/coredns"]
