apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "coredns-gateway.fullname" . }}
  labels:
    {{- include "coredns-gateway.labels" . | nindent 4 }}
  {{- with .Values.customLabels }}
    {{ toYaml . | trim | nindent 4 }}
  {{- end }}
data:
  Corefile: |-
  {{- if gt (len .Values.config.raw) 0 }}
    {{- tpl .Values.config.raw $ | nindent 4 }}
  {{- else }}
    {{- tpl ($.Files.Get (printf "configs/%s.tpl" .Values.config.template)) $ | nindent 4 }}
  {{- end }}
  {{- range .Values.zoneFiles }}
  {{ .filename }}: {{ toYaml .contents | indent 4 }}
  {{- end }}
