{{- $clusterIPs := list -}}
{{- with .Values.service.clusterIPs -}}
  {{- $clusterIPs = splitList "," . -}}
{{- end -}}
apiVersion: v1
kind: Service
metadata:
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "coredns-gateway.labels" . | nindent 4 }}
  {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.customLabels }}
    {{ toYaml . | trim | nindent 4 }}
  {{- end }}
  name: {{ include "coredns-gateway.fullname" . }}
spec:
  selector:
    {{- include "coredns-gateway.selectorLabels" . | nindent 6 }}
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer" }}
    {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
    {{- end }}
  allocateLoadBalancerNodePorts: {{ .Values.service.allocateLoadBalancerNodePorts }}
  {{- end }}
  {{- if or .Values.service.clusterIP .Values.service.clusterIPs }}
  clusterIP: {{ or (first $clusterIPs) .Values.service.clusterIP }}
  {{- end }}
  {{- with .Values.service.clusterIPs }}
  clusterIPs:
    {{- range $clusterIPs }}
    - {{ . }}
    {{- end }}
  {{- end }}
  ports:
  - port: {{ .Values.service.port }}
    protocol: UDP
    name: dns-udp
    targetPort: dns-udp
    {{- if and .Values.service.nodePort (eq .Values.service.type "NodePort") }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  {{- if (eq .Values.service.useTcp true) }}
  - port: {{ .Values.service.port }}
    protocol: TCP
    name: dns-tcp
    targetPort: dns-tcp
    {{- if and .Values.service.nodePort (eq .Values.service.type "NodePort") }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  {{- end }}
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  {{- with .Values.service.externalIPs}}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.service.ipFamilyPolicy }}
  {{- end }}
  {{- with .Values.service.ipFamilies }}
  ipFamilies:
    {{- toYaml . | nindent 4 }}
  {{- end -}}
