{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "coredns-gateway.serviceAccountName" . }}
  labels:
    {{- include "coredns-gateway.labels" . | nindent 4 }}
  {{- with .Values.customLabels }}
    {{ toYaml . | trim | nindent 4 }}
  {{- end }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
