apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: ${releaseName:=k8s_gateway}
spec:
  interval: 10m
  url: oci://${zondaxRegistry}/rawmind/k8s_gateway
  ref:
    tag: ${releaseVersion:=2.5.1-0}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ${releaseName:=k8s_gateway}
spec:
  serviceAccountName: ${serviceAccountHelm}
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: ${releaseName:=k8s_gateway}
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: false
  targetNamespace: ${targetNamespace:=flux-system}
  releaseName: ${releaseName:=k8s_gateway}
  valuesFrom:
    - kind: ConfigMap
      name: ${releaseName:=k8s_gateway}-values
    - kind: ConfigMap
      name: ${k8sGatewayValues:=nonExistent}
      optional: true
