apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: ${releaseName:=coredns-gateway}
spec:
  interval: 10m
  url: oci://${zondaxRegistry}/rawmind/coredns-gateway
  ref:
    tag: ${releaseVersion:=1.12.0}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ${releaseName:=coredns-gateway}
spec:
  serviceAccountName: ${serviceAccountHelm}
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: ${releaseName:=coredns-gateway}
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: false
  targetNamespace: ${targetNamespace:=kube-system}
  releaseName: ${releaseName:=coredns-gateway}
  valuesFrom:
    - kind: ConfigMap
      name: ${releaseName:=coredns-gateway}-values
    - kind: ConfigMap
      name: ${corednsGatewayValues:=nonExistent}
      optional: true
