fullnameOverride: ${releaseName:=coredns-gateway}
replicaCount: 2
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 32Mi

# Delegated domain
domain: ${clusterDomain}
port: 1053
config:
  template: coredns
  raw: |-
    .:{{ .Values.port }} {
      errors
      health {
        lameduck 5s
      }
      ready
      prometheus 0.0.0.0:{{ .Values.config.metrics.port }}
      k8s_gateway {{ .Values.domain }} {
        apex {{ or .Values.apex (include "coredns-gateway.fqdn" .) }}
        ttl 300
        fallthrough {{ .Values.domain }}
      }
    {{- with .Values.config.extraVars.forwardNext }}
      {{- range $k, $v := . }}
      forward {{ $k }} {{ $v }} {
        prefer_udp
        next NXDOMAIN SERVFAIL REFUSED
      }
      {{- end }}
    {{- end }}
      forward . ${clusterDnsUpsIPs:=tls://1.1.1.1:853 tls://1.0.0.1:853 tls://[2606:4700:4700::1111]:853 tls://[2606:4700:4700::1001]:853}
      cache 10
      loop
      reload
      loadbalance
    }

service:
  type: LoadBalancer
  port: 53
  ipFamilyPolicy: PreferDualStack
  clusterIPs: ${clusterDnsExtIPs:=10.43.0.11,fd80:cefa:43::11}
  annotations:
    lbipam.cilium.io/ips: ${clusterDnsVipIPs:=""}

serviceMonitor:
  enabled: true
  interval: 30s
