fullnameOverride: ${releaseName:=coredns_gateway}

replicaCount: 2

# Delegated domain
domain: ${clusterDomain}

# TTL for non-apex responses (in seconds)
ttl: 300

# Enabled fallthrough for coredns_gateway
fallthrough:
  enabled: false
  zones: []

# Optional plugins that will be enabled in the zone, e.g. "forward . /etc/resolve.conf"
extraZonePlugins:
  - name: log
  - name: errors
  # Serves a /health endpoint on :8080, required for livenessProbe
  - name: health
    configBlock: |-
      lameduck 5s
  # Serves a /ready endpoint on :8181, required for readinessProbe
  - name: ready
  # Serves a /metrics endpoint on :9153, required for serviceMonitor
  - name: prometheus
    parameters: 0.0.0.0:9153
  - name: loop
  - name: reload
  - name: loadbalance

service:
  type: LoadBalancer
  port: 53
  ipFamilyPolicy: PreferDualStack
  clusterIPs: ${clusterExtDns:=10.43.0.11,fd80:cefa:43::11}

serviceMonitor:
  enabled: true
  interval: 30s
