name: CI
on:
  push:
    tags-ignore:
      - '*\+chart'
      - '*\+fluxapp'
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - 'deploy/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: goreleaser/goreleaser:v2.7.0
      options: --tty
    steps:
      - name: Requirements
        env:
          GOLANGCI_VERSION: v1.64.5
          GOLANGCI_URL: https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh
        run: |
          curl -sSfL ${GOLANGCI_URL} | sh -s -- -b $(go env GOPATH)/bin ${GOLANGCI_VERSION}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0    # get everything

      - name: Show changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          git config --global --add safe.directory /__w/${REPO_NAME}/${REPO_NAME}
          git diff --name-only -r $(git merge-base --fork-point remotes/origin/master) HEAD | cat

      - name: Build
        if: ${{ github.event_name == 'pull_request' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          make build

      - name: Release
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          GITHUB_URL: ${{ github.event.pull_request.comments_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          make release
